'use client';
import { useEffect, useState } from 'react';
import { WatchListing } from '@/lib/types';
import Link from 'next/link';
import { useAccount, useWriteContract } from 'wagmi';
import { ponsFactoryAbi, PONS_FACTORY } from '@/lib/pons';
import { ConnectButton } from '@rainbow-me/rainbowkit';

export default function Admin(){const [key,setKey]=useState(''); const [watches,setWatches]=useState<WatchListing[]>([]); const [status,setStatus]=useState(''); const {address}=useAccount(); const {writeContract}=useWriteContract();
 async function load(){const r=await fetch('/api/admin/watches',{headers:{'x-timepiece-admin-key':key}}); const j=await r.json(); if(r.ok)setWatches(j.watches); else setStatus(j.error)}
 async function patch(id:string,body:any){const r=await fetch(`/api/admin/watches/${id}`,{method:'PATCH',headers:{'content-type':'application/json','x-timepiece-admin-key':key},body:JSON.stringify(body)}); const j=await r.json(); setStatus(r.ok?'Updated':j.error); if(r.ok) load()}
 async function launchPons(w:WatchListing){ if(!address) return setStatus('Connect admin wallet first.'); const res=await fetch('/api/pons/launch-draft',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...w,creatorFeeRecipient:w.owner_wallet,launcher:address,logo:w.primary_image_url})}); const draft=await res.json(); if(!res.ok) return setStatus(draft.error); if(draft.canLaunch===false) return setStatus('This connected wallet does not currently pass Pons canLaunch().'); writeContract({address:PONS_FACTORY,abi:ponsFactoryAbi,functionName:'launchToken',args:[draft.tokenParams, BigInt(draft.launchConfigId), draft.pairToken], value:BigInt(draft.launchFeeWei)}); setStatus('Wallet transaction opened. After confirmation, paste token/curve addresses into this row.');}
 return <main className="admin-grid"><aside className="sidebar"><Link className="brand" href="/"><span className="brand-mark">↗</span><span>TIMEPIECE</span></Link><p style={{color:'var(--muted)'}}>Admin dashboard</p><div style={{margin:'14px 0'}}><ConnectButton/></div><input className="input" placeholder="Admin key" value={key} onChange={e=>setKey(e.target.value)}/><button className="pill green" style={{marginTop:12}} onClick={load}>Load dashboard</button><p style={{color:'var(--muted)',fontSize:13}}>{status}</p></aside><section className="admin-main"><h1 className="h2 serif" style={{fontSize:64}}>Verification queue</h1><table className="table"><thead><tr><th>Watch</th><th>Owner</th><th>Status</th><th>Value</th><th>Pons token</th><th>Actions</th></tr></thead><tbody>{watches.map(w=><tr key={w.id}><td><b>{w.brand} {w.model}</b><br/><span style={{color:'var(--muted)'}}>{w.reference_number} · {w.year}</span></td><td>{w.owner_wallet?.slice(0,8)}…</td><td>{w.verification_status}</td><td>${w.appraised_value_usd.toLocaleString()}</td><td><input className="input" style={{minWidth:270,marginBottom:8}} placeholder="0x token" defaultValue={w.pons_token_address||''} onBlur={e=>patch(w.id,{pons_token_address:e.target.value||null})}/><input className="input" style={{minWidth:270}} placeholder="0x curve" defaultValue={w.pons_curve_address||''} onBlur={e=>patch(w.id,{pons_curve_address:e.target.value||null})}/></td><td style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="filter" onClick={()=>patch(w.id,{verification_status:'owner_verified'})}>Owner verified</button><button className="filter" onClick={()=>patch(w.id,{verification_status:'authenticated'})}>Authenticated</button><button className="filter" onClick={()=>patch(w.id,{published:!w.published})}>{w.published?'Unpublish':'Publish'}</button><button className="filter active" onClick={()=>launchPons(w)}>Prepare Pons launch</button></td></tr>)}</tbody></table></section></main>}
