'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Nav } from '@/components/Nav';
import { Footer } from '@/components/Footer';
import { WatchListing, TokenMarket } from '@/lib/types';
import { useParams } from 'next/navigation';
import { createChart, ColorType } from 'lightweight-charts';
import { useAccount, useWriteContract } from 'wagmi';
import { parseEther } from 'viem';
import { ponsCurveAbi } from '@/lib/pons';
import { ArrowUpRight } from 'lucide-react';

function PriceChart({market}:{market?:TokenMarket}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{if(!ref.current)return;const chart=createChart(ref.current,{layout:{background:{type:ColorType.Solid,color:'transparent'},textColor:'#aaa89d'},grid:{vertLines:{color:'rgba(255,255,255,.05)'},horzLines:{color:'rgba(255,255,255,.05)'}},rightPriceScale:{borderColor:'rgba(255,255,255,.1)'},timeScale:{borderColor:'rgba(255,255,255,.1)'}});const series=chart.addCandlestickSeries({upColor:'#d5fd51',downColor:'#76776e',borderVisible:false,wickUpColor:'#d5fd51',wickDownColor:'#76776e'});series.setData((market?.candles || []) as any);chart.timeScale().fitContent();return()=>chart.remove()},[market]);return <div className="chart" ref={ref}/>}
export default function WatchDetail(){const params=useParams(); const [watch,setWatch]=useState<WatchListing|null>(null); const [market,setMarket]=useState<TokenMarket|null>(null); const [amount,setAmount]=useState('0.01'); const {address}=useAccount(); const {writeContract}=useWriteContract();
 useEffect(()=>{fetch(`/api/watches/${params.id}`).then(r=>r.json()).then(async d=>{setWatch(d.watch); if(d.watch?.pons_token_address){const m=await fetch(`/api/pons/token/${d.watch.pons_token_address}`).then(r=>r.json()); setMarket(m.market)}})},[params.id]);
 const canTrade = Boolean(watch?.pons_curve_address && address);
 function buy(){ if(!watch?.pons_curve_address||!address) return alert('Connect wallet and attach a curve address first.'); writeContract({address:watch.pons_curve_address as `0x${string}`,abi:ponsCurveAbi,functionName:'buy',args:[parseEther(amount),0n,address],value:parseEther(amount)}); }
 return <main className="page"><Nav/><section className="section" style={{paddingTop:150}}><div className="container split" style={{alignItems:'start'}}><div><div className="watch-art panel" style={{height:520,borderRadius:36}}><div className="mini-watch" style={{width:260,height:260}}/></div><h1 className="h2 serif" style={{fontSize:'clamp(48px,6vw,88px)'}}>{watch?.brand} <em>{watch?.model}</em></h1><p className="lead">{watch?.description}</p></div><div className="panel" style={{padding:28}}><div className="kicker">Token Market</div><h2 style={{fontSize:36,margin:'12px 0'}}>{watch?.reference_number || 'Verified watch'}</h2><div className="metric-row"><div className="metric"><span>Appraised</span><b>${watch?.appraised_value_usd?.toLocaleString()}</b></div><div className="metric"><span>Holders</span><b>{market?.holders ?? '—'}</b></div><div className="metric"><span>Condition</span><b>{watch?.condition}</b></div><div className="metric"><span>Status</span><b>{watch?.verification_status?.replace('_',' ')}</b></div></div><div style={{margin:'24px 0'}}><PriceChart market={market||undefined}/>{!market?.candles?.length&&<p style={{color:'var(--muted)',fontSize:13}}>No indexed trade candles yet. Add the Pons indexer in README_DATABASE to show real OHLC history.</p>}</div><label className="label">ETH amount<input className="input" value={amount} onChange={e=>setAmount(e.target.value)}/></label><button className="pill green" style={{marginTop:14,width:'100%',justifyContent:'center'}} onClick={buy}>Buy watch token <ArrowUpRight size={16}/></button><p style={{color:'var(--muted)',fontSize:13}}>Before graduation, trades route to the Pons curve. After graduation, route the token through its Uniswap v4 pool.</p></div></div></section><Footer/></main>}
